name: auren
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  fl_chart: ^1.0.0
  intl: ^0.20.2
  google_maps_flutter: ^2.6.0
  geolocator: ^12.0.0
  permission_handler: ^12.0.0+1
  http: ^1.5.0
  equatable: ^2.0.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_auren_logo.png"
  adaptive_icon_background: "#4ECDC4"
  adaptive_icon_foreground: "assets/images/ic_auren_logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/ic_auren_logo.png
  android: true
  ios: true